apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-nfs-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/data/pgsqldata"
    server: #nfs-server-running-ip

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgsql-nfs-pvc
  labels:
    app: postgres
spec:
  capacity:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgsql-terraform-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: 'awesomedb'
  POSTGRES_USER: 'amazinguser'
  POSTGRES_PASSWORD: 'perfectpassword'

---
apiVersion: v1
kind: Service
metadata:
  name: pgsql-terraform-svc
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
    nodePort: 31186
  type: NodePort 
  selector:
    app: postgres
    
#---
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: postgres-pv
#  labels:
#    app: postgres
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/var/data/pgsqldata"
#
#---
#
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: postgres-pvc
#  labels:
#    app: postgres
#spec:
#  storageClassName: manual
#  capacity:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
        
