global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m

  receiver: "default"
  routes:
   - match:
      severity: info
     receiver: slack

   - match:
      severity: critical
     receiver: email

receivers:
  - name: default
    email_configs:
     - to: 'xyz@gmail.com'
       from: 'xyz@gmail.com'
       smarthost: 'smtp.office365.com:587'
       auth_username: "xyz@gmail.com"
       auth_password: "Password123"
       require_tls: true
       html: '{{ template "email" .}}'

  - name: slack
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: '#alertmanager'
        username: '{{ template "slack.default.username" . }}'
        color: '{{ if eq .Status "firing" }}good{{ else }}good{{ end }}'
        title: '{{ template "slack.default.title" . }}'
        title_link: '{{ template "slack.default.titlelink" . }}'
        pretext: '{{ .CommonAnnotations.summary }}'
        text:
         >-
          {{ range .Alerts }}
           *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`:bar_chart:
           *Description:* {{ .Annotations.description }}
           *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
           {{ end }}
          {{ end }}
  
  - name: email
    email_configs:
     - to: 'xyz@gmail.com'
       from: 'xyz@gmail.com'
       smarthost: 'smtp.office365.com:587'
       auth_username: "xyz@gmail.com"
       auth_password: "Password123"
       require_tls: true
       html: '{{ template "email" .}}'

templates:
- './alert.tmpl'
